### ISSUE TITLE
Typographical mistakes 

### ISSUE THREAD

**Issue by ssepehrnoush** [ODC-TEH/localmail#1]
# Typographical mistakes

in order for the users to install the program properly they must create an SQL server ,but in  [QUICKSTART Toturial](https://github.com/ODC-TEH/localmail/blame/master/README.md) there is a small misspelled word in (line 31)postgresql codes / you may change "catalog" to "catuser"
![2016-06-13_11-32-14](https://cloud.githubusercontent.com/assets/17469853/15999546/bc8fabe8-315b-11e6-8f18-4cc519052f43.png)

**Comment by sepehrnoush** [comment]
Done!

**Comment by sepehrnoush** [comment]
fixed

**Comment by ssepehrnoush** [comment]
there is 2 more 
line 40 & 41 :
sudo cp localmaildbRootfolder/localmaildb.conf /etc/apache2/available-sites/
sudo a2ensite localmaildb
it must change to :  
sudo cp localmaildbRootfolder/localmaildb.conf /etc/apache2/**sites-available**/
sudo a2ensite **localmaildb.conf**
